name: app

services:
  redis:
    image: redis:7.4.3-alpine
    container_name: django-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:15.3-alpine3.18
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5332:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  web:
    build: .
    container_name: django-app
    command: python -u manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok
    depends_on:
      - web
    command: http web:8000
    environment:
      NGROK_AUTHTOKEN: ${NGROCK_KEY}
    ports:
      - "4040:4040"

volumes:
  db-data:
  redis_data: