# Generated by Django 6.0.1 on 2026-01-13 21:10

import mainapp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_searchinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=mainapp.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=mainapp.fields.EncryptedTextField(),
        ),
    ]
